#my.greeting=Hello World
#my.list.values=One,Two,Three
#dbValues={connectionString: 'http://___', userName: 'foo', password: 'pass'}

#db.connection={connectionString: 'http://___', userName: 'foo', password: 'pass'}
#db.host=127.0.0.1
#db.port=1200

#management.endpoints.web.exposure.include=*

db:
   connection: test-connection-string-here
   host: 129.0.0.1
   port: 2400

management.endpoints.web.exposure.include: "*"