#my.greeting=Hello World
#my.list.values=One,Two,Three
#dbValues={connectionString: 'http://___', userName: 'foo', password: 'pass'}

#db.connection={connectionString: 'http://___', userName: 'foo', password: 'pass'}
#db.host=127.0.0.1
#db.port=1200

#management.endpoints.web.exposure.include=*

#db:
#   connection: "{connectionString: 'http://___', userName: 'foo', password: 'pass'}"
#   host: 127.0.0.1
#   port: 1200
my:
 greeting: Hello World
 
 list:
  values: One, Two, Three
  
  
management.endpoints.web.exposure.include: "*"
#spring.profiles.active: test

spring.cloud.config.uri: http://localhost:8888